MQTT_USERNAME = "ssr-baton-test@ttn"
MQTT_PASSWORD = "NNSXS.Q2TYZ6MNINBWG4MDDC7KOCWU3NRWIBKTU5QDGYA.ILKJTCXVLQ3BWHWYM2WTNMCJRMO4B7IJYQERVX5HOIQTAGRQOFQQ"
MQTT_SERVER = "nam1.cloud.thethings.network"
APP_ID = "ssr-baton-test"